##Vim プラグイン管理
####################

[[plugins]]
repo = 'Shougo/dein.vim'

#colorscheme
[[plugins]]
repo = 'jnurmine/Zenburn'

##vim ユーティリティ
####################

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
nnoremap <silent>F :call OpenDeniteBufferDirFile()<CR>
let s:denite_win_width_percent = 1
let s:denite_win_height_percent = 0.5

function! OpenDeniteBufferDirFile()
  " Update denite default options
  call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
    \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
    \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
    \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) - 2),
    \ })
  DeniteBufferDir file file:new
  highlight NormalFloat ctermbg=black guibg=none
endfunction
'''

[plugins.ftplugin]
denite = '''
nnoremap <silent><buffer><expr> <CR>  denite#do_map('do_action')
nnoremap <silent><buffer><expr> l     denite#do_map('do_action')
nnoremap <silent><buffer><expr> <BS>  denite#do_map('move_up_path')
nnoremap <silent><buffer><expr> h     denite#do_map('move_up_path')
nnoremap <silent><buffer><expr> <esc> denite#do_map('quit')
nnoremap <silent><buffer><expr> q     denite#do_map('quit')
nnoremap <silent><buffer><expr> p     denite#do_map('do_action', 'preview')
nnoremap <silent><buffer><expr> i     denite#do_map('open_filter_buffer')
'''

[[plugins]]
repo = 'k15uk/ibus_toggle.vim'
hook_add = '''
let g:ibus_toggle_default_im = 'xkb:us::eng'
'''

##テキスト編集機能拡張
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
depends = [ 'async.vim' ]

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = [ 'async.vim' ]
hook_add = '''
  setlocal omnifunc=lsp#complete
  nnoremap <silent><leader>j :LspDefinition<CR>
  nnoremap <silent><leader>h :LspHover<CR>
  let g:lsp_diagnostics_echo_cursor = 1
  let g:lsp_async_completion = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = [ 'vim-lsp']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
depends = [ 'vim-lsp']

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = [ 'vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = [ 'asyncomplete.vim', 'vim-lsp']

#bufferをタブバーに表示
[[plugins]]
repo = 'ap/vim-buftabline'

#ステータスライン表示拡張
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left'  : [ [ 'mode', 'paste' ],
  \               [ 'filename' , 'readonly'],
  \               [ 'modified' ]
  \             ],
  \    'right' : [ [ 'lineinfo'],
  \               [ 'percent' ],
  \               [ 'fileencoding', 'fileformat', 'filetype' ]
  \             ],
  \           },
  \ 'component_function': {
  \   },
  \ }
'''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'

#コメントをトグル
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  nnoremap ,, :TComment<CR>
  vnoremap ,, :TComment<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

# vim:fenc=utf-8 ff=unix ft=conf
