### denite ###
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = [ 'Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir' ]
hook_install = ':UpdateRemotePlugins'
hook_source = '''
  let s:denite_win_width_percent = 1
  let s:denite_win_height_percent = 0.5

  call denite#custom#option( 'default', {
    \ 'split':     'floating',
    \ 'winwidth':  float2nr( &columns * s:denite_win_width_percent ),
    \ 'wincol':    float2nr( ( &columns - ( &columns * s:denite_win_width_percent ) ) / 2 ),
    \ 'winheight': float2nr( &lines * s:denite_win_height_percent ),
    \ 'winrow':    float2nr( ( &lines - ( &lines * s:denite_win_height_percent ) ) - 2 ),
    \ } )

  highlight NormalFloat ctermbg=black guibg=none
  call denite#custom#source( 'file', 'sorters', [ 'sorter/word' ] )
  call denite#custom#option( 'file', {
    \ 'split':     'floating',
    \ 'winwidth':  float2nr( &columns / 4 ),
    \ 'wincol':    0,
    \ 'winheight': float2nr( &lines * 1 ) - 2,
    \ 'winrow':    0,
    \ } )

  call denite#custom#source( 'file/rec', 'sorters', [ 'sorter/word' ] )
  call denite#custom#source( 'file/rec', 'matchers', [ 'matcher/fuzzy' ] )
'''

hook_add = '''
  nnoremap <silent>F :DeniteBufferDir -buffer-name=file file file:new<CR>
  nnoremap <silent><Tab>   :Denite buffer<CR> :call Denite_settings()<CR>
  nnoremap <silent><S-Tab> :Denite buffer<CR> :call Denite_settings()<CR>

  function! Denite_settings() abort
    nnoremap <silent><buffer><expr> <Tab> (line('.') == line('$')) ? 'gg' : 'j'
    nnoremap <silent><buffer><expr> <S-Tab> (line('.') == '1' ) ? 'G' : 'k'
    nnoremap <silent><buffer> h     :execute ':bwipeout ' split( getline( line('.')) , '\s\+' )[2]<CR>:close<CR>
  endfunction

  autocmd FileType denite-filter call s:denite_filter_settings()
  function! s:denite_filter_settings() abort
    inoremap <silent><buffer><expr> <Esc>   denite#do_map( 'quit' )
  endfunction
'''

[plugins.ftplugin]
denite = '''
  nnoremap <silent><buffer><expr> <CR>  denite#do_map( 'do_action' )
  nnoremap <silent><buffer><expr> l     denite#do_map( 'do_action' )
  nnoremap <silent><buffer><expr> h     denite#do_map( 'move_up_path' )
  nnoremap <silent><buffer><expr> <Esc> denite#do_map( 'quit' )
  nnoremap <silent><buffer><expr> i     denite#do_map( 'open_filter_buffer' )
'''

### 各言語ごとの設定 ###

[[plugins]]
# syntax for vue
repo = 'posva/vim-vue'
on_ft = [ 'vue' ]

[[plugins]]
# syntax for pug
repo = 'digitaltoad/vim-pug'
on_ft = [ 'vue' , 'pug' ]

[[plugins]]
# syntax and autocomplete for stylus
repo = 'iloginow/vim-stylus'
on_ft = [ 'vue' , 'stylus' ]

[[plugins]]
# syntax for toml
repo = 'cespare/vim-toml'
on_ft = [ 'toml' ]

[[plugins]]
# syntax for plantuml
repo = 'aklt/plantuml-syntax'
on_ft = [ 'uml' , 'plantuml' ]

[[plugins]]
# SQL formatter
repo = 'mattn/vim-sqlfmt'
on_cmd = [ 'SQLfmt' ]

# vim:fenc=utf-8 ff=unix ft=toml
